/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSyncIndexRouteImport } from './routes/_authenticated/sync/index'
import { Route as AuthenticatedTenantsTenantSlugRouteImport } from './routes/_authenticated/tenants/$tenantSlug'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedWebhooksIndexRouteImport } from './routes/_authenticated/webhooks/index'
import { Route as AuthenticatedWebhooksWebhookIdRouteImport } from './routes/_authenticated/webhooks/$webhookId'
import { Route as AuthenticatedWebhooksNewRouteImport } from './routes/_authenticated/webhooks/new'
import { Route as AuthenticatedAdminTenantsIndexRouteImport } from './routes/_authenticated/admin/tenants/index'
import { Route as AuthenticatedAdminTenantsTenantSlugRouteImport } from './routes/_authenticated/admin/tenants/$tenantSlug'
import { Route as AuthenticatedAdminTenantsNewRouteImport } from './routes/_authenticated/admin/tenants/new'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedTenantsTenantSlugSplatRouteImport } from './routes/_authenticated/tenants/$tenantSlug/$'
import { Route as AuthenticatedTenantsTenantSlugSettingsRouteRouteImport } from './routes/_authenticated/tenants/$tenantSlug/settings/route'
import { Route as AuthenticatedTenantsTenantSlugAiImportReviewRouteImport } from './routes/_authenticated/tenants/$tenantSlug/ai/import-review'
import { Route as AuthenticatedTenantsTenantSlugCollectionsIndexRouteImport } from './routes/_authenticated/tenants/$tenantSlug/collections/index'
import { Route as AuthenticatedTenantsTenantSlugCollectionsCreateRouteImport } from './routes/_authenticated/tenants/$tenantSlug/collections/create'
import { Route as AuthenticatedTenantsTenantSlugCollectionsCreateSingletonRouteImport } from './routes/_authenticated/tenants/$tenantSlug/collections/create-singleton'
import { Route as AuthenticatedTenantsTenantSlugMediaIndexRouteImport } from './routes/_authenticated/tenants/$tenantSlug/media/index'
import { Route as AuthenticatedTenantsTenantSlugPluginsIndexRouteImport } from './routes/_authenticated/tenants/$tenantSlug/plugins/index'
import { Route as AuthenticatedTenantsTenantSlugPublishingIndexRouteImport } from './routes/_authenticated/tenants/$tenantSlug/publishing/index'
import { Route as AuthenticatedTenantsTenantSlugSettingsIndexRouteImport } from './routes/_authenticated/tenants/$tenantSlug/settings/index'
import { Route as AuthenticatedTenantsTenantSlugSettingsAccountRouteImport } from './routes/_authenticated/tenants/$tenantSlug/settings/account'
import { Route as AuthenticatedTenantsTenantSlugSettingsAppearanceRouteImport } from './routes/_authenticated/tenants/$tenantSlug/settings/appearance'
import { Route as AuthenticatedTenantsTenantSlugSettingsDisplayRouteImport } from './routes/_authenticated/tenants/$tenantSlug/settings/display'
import { Route as AuthenticatedTenantsTenantSlugSettingsNotificationsRouteImport } from './routes/_authenticated/tenants/$tenantSlug/settings/notifications'
import { Route as AuthenticatedTenantsTenantSlugSyncIndexRouteImport } from './routes/_authenticated/tenants/$tenantSlug/sync/index'
import { Route as AuthenticatedTenantsTenantSlugUsersIndexRouteImport } from './routes/_authenticated/tenants/$tenantSlug/users/index'
import { Route as AuthenticatedTenantsTenantSlugWebhooksIndexRouteImport } from './routes/_authenticated/tenants/$tenantSlug/webhooks/index'
import { Route as AuthenticatedTenantsTenantSlugWebhooksWebhookIdRouteImport } from './routes/_authenticated/tenants/$tenantSlug/webhooks/$webhookId'
import { Route as AuthenticatedTenantsTenantSlugWebhooksNewRouteImport } from './routes/_authenticated/tenants/$tenantSlug/webhooks/new'
import { Route as AuthenticatedTenantsTenantSlugCollectionsCollectionIdIndexRouteImport } from './routes/_authenticated/tenants/$tenantSlug/collections/$collectionId/index'
import { Route as AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesIndexRouteImport } from './routes/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/index'
import { Route as AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesCreateRouteImport } from './routes/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/create'
import { Route as AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesEntryIdIndexRouteImport } from './routes/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/$entryId/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSyncIndexRoute = AuthenticatedSyncIndexRouteImport.update({
  id: '/sync/',
  path: '/sync/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsTenantSlugRoute =
  AuthenticatedTenantsTenantSlugRouteImport.update({
    id: '/tenants/$tenantSlug',
    path: '/tenants/$tenantSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebhooksIndexRoute =
  AuthenticatedWebhooksIndexRouteImport.update({
    id: '/webhooks/',
    path: '/webhooks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebhooksWebhookIdRoute =
  AuthenticatedWebhooksWebhookIdRouteImport.update({
    id: '/webhooks/$webhookId',
    path: '/webhooks/$webhookId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebhooksNewRoute =
  AuthenticatedWebhooksNewRouteImport.update({
    id: '/webhooks/new',
    path: '/webhooks/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTenantsIndexRoute =
  AuthenticatedAdminTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTenantsTenantSlugRoute =
  AuthenticatedAdminTenantsTenantSlugRouteImport.update({
    id: '/tenants/$tenantSlug',
    path: '/tenants/$tenantSlug',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTenantsNewRoute =
  AuthenticatedAdminTenantsNewRouteImport.update({
    id: '/tenants/new',
    path: '/tenants/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedTenantsTenantSlugSplatRoute =
  AuthenticatedTenantsTenantSlugSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugSettingsRouteRoute =
  AuthenticatedTenantsTenantSlugSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugAiImportReviewRoute =
  AuthenticatedTenantsTenantSlugAiImportReviewRouteImport.update({
    id: '/ai/import-review',
    path: '/ai/import-review',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugCollectionsIndexRoute =
  AuthenticatedTenantsTenantSlugCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugCollectionsCreateRoute =
  AuthenticatedTenantsTenantSlugCollectionsCreateRouteImport.update({
    id: '/collections/create',
    path: '/collections/create',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugCollectionsCreateSingletonRoute =
  AuthenticatedTenantsTenantSlugCollectionsCreateSingletonRouteImport.update({
    id: '/collections/create-singleton',
    path: '/collections/create-singleton',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugMediaIndexRoute =
  AuthenticatedTenantsTenantSlugMediaIndexRouteImport.update({
    id: '/media/',
    path: '/media/',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugPluginsIndexRoute =
  AuthenticatedTenantsTenantSlugPluginsIndexRouteImport.update({
    id: '/plugins/',
    path: '/plugins/',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugPublishingIndexRoute =
  AuthenticatedTenantsTenantSlugPublishingIndexRouteImport.update({
    id: '/publishing/',
    path: '/publishing/',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugSettingsIndexRoute =
  AuthenticatedTenantsTenantSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTenantsTenantSlugSettingsRouteRoute,
  } as any)
const AuthenticatedTenantsTenantSlugSettingsAccountRoute =
  AuthenticatedTenantsTenantSlugSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedTenantsTenantSlugSettingsRouteRoute,
  } as any)
const AuthenticatedTenantsTenantSlugSettingsAppearanceRoute =
  AuthenticatedTenantsTenantSlugSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedTenantsTenantSlugSettingsRouteRoute,
  } as any)
const AuthenticatedTenantsTenantSlugSettingsDisplayRoute =
  AuthenticatedTenantsTenantSlugSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedTenantsTenantSlugSettingsRouteRoute,
  } as any)
const AuthenticatedTenantsTenantSlugSettingsNotificationsRoute =
  AuthenticatedTenantsTenantSlugSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedTenantsTenantSlugSettingsRouteRoute,
  } as any)
const AuthenticatedTenantsTenantSlugSyncIndexRoute =
  AuthenticatedTenantsTenantSlugSyncIndexRouteImport.update({
    id: '/sync/',
    path: '/sync/',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugUsersIndexRoute =
  AuthenticatedTenantsTenantSlugUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugWebhooksIndexRoute =
  AuthenticatedTenantsTenantSlugWebhooksIndexRouteImport.update({
    id: '/webhooks/',
    path: '/webhooks/',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugWebhooksWebhookIdRoute =
  AuthenticatedTenantsTenantSlugWebhooksWebhookIdRouteImport.update({
    id: '/webhooks/$webhookId',
    path: '/webhooks/$webhookId',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugWebhooksNewRoute =
  AuthenticatedTenantsTenantSlugWebhooksNewRouteImport.update({
    id: '/webhooks/new',
    path: '/webhooks/new',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugCollectionsCollectionIdIndexRoute =
  AuthenticatedTenantsTenantSlugCollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collectionId/',
    path: '/collections/$collectionId/',
    getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
  } as any)
const AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesIndexRoute =
  AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesIndexRouteImport.update(
    {
      id: '/collections/$collectionId/entries/',
      path: '/collections/$collectionId/entries/',
      getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
    } as any,
  )
const AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesCreateRoute =
  AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesCreateRouteImport.update(
    {
      id: '/collections/$collectionId/entries/create',
      path: '/collections/$collectionId/entries/create',
      getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
    } as any,
  )
const AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesEntryIdIndexRoute =
  AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesEntryIdIndexRouteImport.update(
    {
      id: '/collections/$collectionId/entries/$entryId/',
      path: '/collections/$collectionId/entries/$entryId/',
      getParentRoute: () => AuthenticatedTenantsTenantSlugRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/tenants/$tenantSlug': typeof AuthenticatedTenantsTenantSlugRouteWithChildren
  '/webhooks/$webhookId': typeof AuthenticatedWebhooksWebhookIdRoute
  '/webhooks/new': typeof AuthenticatedWebhooksNewRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/sync/': typeof AuthenticatedSyncIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/webhooks/': typeof AuthenticatedWebhooksIndexRoute
  '/tenants/$tenantSlug/settings': typeof AuthenticatedTenantsTenantSlugSettingsRouteRouteWithChildren
  '/admin/tenants/$tenantSlug': typeof AuthenticatedAdminTenantsTenantSlugRoute
  '/admin/tenants/new': typeof AuthenticatedAdminTenantsNewRoute
  '/tenants/$tenantSlug/$': typeof AuthenticatedTenantsTenantSlugSplatRoute
  '/admin/tenants/': typeof AuthenticatedAdminTenantsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/tenants/$tenantSlug/ai/import-review': typeof AuthenticatedTenantsTenantSlugAiImportReviewRoute
  '/tenants/$tenantSlug/collections/create': typeof AuthenticatedTenantsTenantSlugCollectionsCreateRoute
  '/tenants/$tenantSlug/collections/create-singleton': typeof AuthenticatedTenantsTenantSlugCollectionsCreateSingletonRoute
  '/tenants/$tenantSlug/settings/account': typeof AuthenticatedTenantsTenantSlugSettingsAccountRoute
  '/tenants/$tenantSlug/settings/appearance': typeof AuthenticatedTenantsTenantSlugSettingsAppearanceRoute
  '/tenants/$tenantSlug/settings/display': typeof AuthenticatedTenantsTenantSlugSettingsDisplayRoute
  '/tenants/$tenantSlug/settings/notifications': typeof AuthenticatedTenantsTenantSlugSettingsNotificationsRoute
  '/tenants/$tenantSlug/webhooks/$webhookId': typeof AuthenticatedTenantsTenantSlugWebhooksWebhookIdRoute
  '/tenants/$tenantSlug/webhooks/new': typeof AuthenticatedTenantsTenantSlugWebhooksNewRoute
  '/tenants/$tenantSlug/collections/': typeof AuthenticatedTenantsTenantSlugCollectionsIndexRoute
  '/tenants/$tenantSlug/media/': typeof AuthenticatedTenantsTenantSlugMediaIndexRoute
  '/tenants/$tenantSlug/plugins/': typeof AuthenticatedTenantsTenantSlugPluginsIndexRoute
  '/tenants/$tenantSlug/publishing/': typeof AuthenticatedTenantsTenantSlugPublishingIndexRoute
  '/tenants/$tenantSlug/settings/': typeof AuthenticatedTenantsTenantSlugSettingsIndexRoute
  '/tenants/$tenantSlug/sync/': typeof AuthenticatedTenantsTenantSlugSyncIndexRoute
  '/tenants/$tenantSlug/users/': typeof AuthenticatedTenantsTenantSlugUsersIndexRoute
  '/tenants/$tenantSlug/webhooks/': typeof AuthenticatedTenantsTenantSlugWebhooksIndexRoute
  '/tenants/$tenantSlug/collections/$collectionId/': typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdIndexRoute
  '/tenants/$tenantSlug/collections/$collectionId/entries/create': typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesCreateRoute
  '/tenants/$tenantSlug/collections/$collectionId/entries/': typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesIndexRoute
  '/tenants/$tenantSlug/collections/$collectionId/entries/$entryId/': typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesEntryIdIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/tenants/$tenantSlug': typeof AuthenticatedTenantsTenantSlugRouteWithChildren
  '/webhooks/$webhookId': typeof AuthenticatedWebhooksWebhookIdRoute
  '/webhooks/new': typeof AuthenticatedWebhooksNewRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/sync': typeof AuthenticatedSyncIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/webhooks': typeof AuthenticatedWebhooksIndexRoute
  '/admin/tenants/$tenantSlug': typeof AuthenticatedAdminTenantsTenantSlugRoute
  '/admin/tenants/new': typeof AuthenticatedAdminTenantsNewRoute
  '/tenants/$tenantSlug/$': typeof AuthenticatedTenantsTenantSlugSplatRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/tenants/$tenantSlug/ai/import-review': typeof AuthenticatedTenantsTenantSlugAiImportReviewRoute
  '/tenants/$tenantSlug/collections/create': typeof AuthenticatedTenantsTenantSlugCollectionsCreateRoute
  '/tenants/$tenantSlug/collections/create-singleton': typeof AuthenticatedTenantsTenantSlugCollectionsCreateSingletonRoute
  '/tenants/$tenantSlug/settings/account': typeof AuthenticatedTenantsTenantSlugSettingsAccountRoute
  '/tenants/$tenantSlug/settings/appearance': typeof AuthenticatedTenantsTenantSlugSettingsAppearanceRoute
  '/tenants/$tenantSlug/settings/display': typeof AuthenticatedTenantsTenantSlugSettingsDisplayRoute
  '/tenants/$tenantSlug/settings/notifications': typeof AuthenticatedTenantsTenantSlugSettingsNotificationsRoute
  '/tenants/$tenantSlug/webhooks/$webhookId': typeof AuthenticatedTenantsTenantSlugWebhooksWebhookIdRoute
  '/tenants/$tenantSlug/webhooks/new': typeof AuthenticatedTenantsTenantSlugWebhooksNewRoute
  '/tenants/$tenantSlug/collections': typeof AuthenticatedTenantsTenantSlugCollectionsIndexRoute
  '/tenants/$tenantSlug/media': typeof AuthenticatedTenantsTenantSlugMediaIndexRoute
  '/tenants/$tenantSlug/plugins': typeof AuthenticatedTenantsTenantSlugPluginsIndexRoute
  '/tenants/$tenantSlug/publishing': typeof AuthenticatedTenantsTenantSlugPublishingIndexRoute
  '/tenants/$tenantSlug/settings': typeof AuthenticatedTenantsTenantSlugSettingsIndexRoute
  '/tenants/$tenantSlug/sync': typeof AuthenticatedTenantsTenantSlugSyncIndexRoute
  '/tenants/$tenantSlug/users': typeof AuthenticatedTenantsTenantSlugUsersIndexRoute
  '/tenants/$tenantSlug/webhooks': typeof AuthenticatedTenantsTenantSlugWebhooksIndexRoute
  '/tenants/$tenantSlug/collections/$collectionId': typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdIndexRoute
  '/tenants/$tenantSlug/collections/$collectionId/entries/create': typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesCreateRoute
  '/tenants/$tenantSlug/collections/$collectionId/entries': typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesIndexRoute
  '/tenants/$tenantSlug/collections/$collectionId/entries/$entryId': typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesEntryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/tenants/$tenantSlug': typeof AuthenticatedTenantsTenantSlugRouteWithChildren
  '/_authenticated/webhooks/$webhookId': typeof AuthenticatedWebhooksWebhookIdRoute
  '/_authenticated/webhooks/new': typeof AuthenticatedWebhooksNewRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/sync/': typeof AuthenticatedSyncIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/webhooks/': typeof AuthenticatedWebhooksIndexRoute
  '/_authenticated/tenants/$tenantSlug/settings': typeof AuthenticatedTenantsTenantSlugSettingsRouteRouteWithChildren
  '/_authenticated/admin/tenants/$tenantSlug': typeof AuthenticatedAdminTenantsTenantSlugRoute
  '/_authenticated/admin/tenants/new': typeof AuthenticatedAdminTenantsNewRoute
  '/_authenticated/tenants/$tenantSlug/$': typeof AuthenticatedTenantsTenantSlugSplatRoute
  '/_authenticated/admin/tenants/': typeof AuthenticatedAdminTenantsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/tenants/$tenantSlug/ai/import-review': typeof AuthenticatedTenantsTenantSlugAiImportReviewRoute
  '/_authenticated/tenants/$tenantSlug/collections/create': typeof AuthenticatedTenantsTenantSlugCollectionsCreateRoute
  '/_authenticated/tenants/$tenantSlug/collections/create-singleton': typeof AuthenticatedTenantsTenantSlugCollectionsCreateSingletonRoute
  '/_authenticated/tenants/$tenantSlug/settings/account': typeof AuthenticatedTenantsTenantSlugSettingsAccountRoute
  '/_authenticated/tenants/$tenantSlug/settings/appearance': typeof AuthenticatedTenantsTenantSlugSettingsAppearanceRoute
  '/_authenticated/tenants/$tenantSlug/settings/display': typeof AuthenticatedTenantsTenantSlugSettingsDisplayRoute
  '/_authenticated/tenants/$tenantSlug/settings/notifications': typeof AuthenticatedTenantsTenantSlugSettingsNotificationsRoute
  '/_authenticated/tenants/$tenantSlug/webhooks/$webhookId': typeof AuthenticatedTenantsTenantSlugWebhooksWebhookIdRoute
  '/_authenticated/tenants/$tenantSlug/webhooks/new': typeof AuthenticatedTenantsTenantSlugWebhooksNewRoute
  '/_authenticated/tenants/$tenantSlug/collections/': typeof AuthenticatedTenantsTenantSlugCollectionsIndexRoute
  '/_authenticated/tenants/$tenantSlug/media/': typeof AuthenticatedTenantsTenantSlugMediaIndexRoute
  '/_authenticated/tenants/$tenantSlug/plugins/': typeof AuthenticatedTenantsTenantSlugPluginsIndexRoute
  '/_authenticated/tenants/$tenantSlug/publishing/': typeof AuthenticatedTenantsTenantSlugPublishingIndexRoute
  '/_authenticated/tenants/$tenantSlug/settings/': typeof AuthenticatedTenantsTenantSlugSettingsIndexRoute
  '/_authenticated/tenants/$tenantSlug/sync/': typeof AuthenticatedTenantsTenantSlugSyncIndexRoute
  '/_authenticated/tenants/$tenantSlug/users/': typeof AuthenticatedTenantsTenantSlugUsersIndexRoute
  '/_authenticated/tenants/$tenantSlug/webhooks/': typeof AuthenticatedTenantsTenantSlugWebhooksIndexRoute
  '/_authenticated/tenants/$tenantSlug/collections/$collectionId/': typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdIndexRoute
  '/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/create': typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesCreateRoute
  '/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/': typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesIndexRoute
  '/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/$entryId/': typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesEntryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/tenants/$tenantSlug'
    | '/webhooks/$webhookId'
    | '/webhooks/new'
    | '/settings/'
    | '/sync/'
    | '/users/'
    | '/webhooks/'
    | '/tenants/$tenantSlug/settings'
    | '/admin/tenants/$tenantSlug'
    | '/admin/tenants/new'
    | '/tenants/$tenantSlug/$'
    | '/admin/tenants/'
    | '/admin/users/'
    | '/tenants/$tenantSlug/ai/import-review'
    | '/tenants/$tenantSlug/collections/create'
    | '/tenants/$tenantSlug/collections/create-singleton'
    | '/tenants/$tenantSlug/settings/account'
    | '/tenants/$tenantSlug/settings/appearance'
    | '/tenants/$tenantSlug/settings/display'
    | '/tenants/$tenantSlug/settings/notifications'
    | '/tenants/$tenantSlug/webhooks/$webhookId'
    | '/tenants/$tenantSlug/webhooks/new'
    | '/tenants/$tenantSlug/collections/'
    | '/tenants/$tenantSlug/media/'
    | '/tenants/$tenantSlug/plugins/'
    | '/tenants/$tenantSlug/publishing/'
    | '/tenants/$tenantSlug/settings/'
    | '/tenants/$tenantSlug/sync/'
    | '/tenants/$tenantSlug/users/'
    | '/tenants/$tenantSlug/webhooks/'
    | '/tenants/$tenantSlug/collections/$collectionId/'
    | '/tenants/$tenantSlug/collections/$collectionId/entries/create'
    | '/tenants/$tenantSlug/collections/$collectionId/entries/'
    | '/tenants/$tenantSlug/collections/$collectionId/entries/$entryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/tenants/$tenantSlug'
    | '/webhooks/$webhookId'
    | '/webhooks/new'
    | '/settings'
    | '/sync'
    | '/users'
    | '/webhooks'
    | '/admin/tenants/$tenantSlug'
    | '/admin/tenants/new'
    | '/tenants/$tenantSlug/$'
    | '/admin/tenants'
    | '/admin/users'
    | '/tenants/$tenantSlug/ai/import-review'
    | '/tenants/$tenantSlug/collections/create'
    | '/tenants/$tenantSlug/collections/create-singleton'
    | '/tenants/$tenantSlug/settings/account'
    | '/tenants/$tenantSlug/settings/appearance'
    | '/tenants/$tenantSlug/settings/display'
    | '/tenants/$tenantSlug/settings/notifications'
    | '/tenants/$tenantSlug/webhooks/$webhookId'
    | '/tenants/$tenantSlug/webhooks/new'
    | '/tenants/$tenantSlug/collections'
    | '/tenants/$tenantSlug/media'
    | '/tenants/$tenantSlug/plugins'
    | '/tenants/$tenantSlug/publishing'
    | '/tenants/$tenantSlug/settings'
    | '/tenants/$tenantSlug/sync'
    | '/tenants/$tenantSlug/users'
    | '/tenants/$tenantSlug/webhooks'
    | '/tenants/$tenantSlug/collections/$collectionId'
    | '/tenants/$tenantSlug/collections/$collectionId/entries/create'
    | '/tenants/$tenantSlug/collections/$collectionId/entries'
    | '/tenants/$tenantSlug/collections/$collectionId/entries/$entryId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/tenants/$tenantSlug'
    | '/_authenticated/webhooks/$webhookId'
    | '/_authenticated/webhooks/new'
    | '/_authenticated/settings/'
    | '/_authenticated/sync/'
    | '/_authenticated/users/'
    | '/_authenticated/webhooks/'
    | '/_authenticated/tenants/$tenantSlug/settings'
    | '/_authenticated/admin/tenants/$tenantSlug'
    | '/_authenticated/admin/tenants/new'
    | '/_authenticated/tenants/$tenantSlug/$'
    | '/_authenticated/admin/tenants/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/tenants/$tenantSlug/ai/import-review'
    | '/_authenticated/tenants/$tenantSlug/collections/create'
    | '/_authenticated/tenants/$tenantSlug/collections/create-singleton'
    | '/_authenticated/tenants/$tenantSlug/settings/account'
    | '/_authenticated/tenants/$tenantSlug/settings/appearance'
    | '/_authenticated/tenants/$tenantSlug/settings/display'
    | '/_authenticated/tenants/$tenantSlug/settings/notifications'
    | '/_authenticated/tenants/$tenantSlug/webhooks/$webhookId'
    | '/_authenticated/tenants/$tenantSlug/webhooks/new'
    | '/_authenticated/tenants/$tenantSlug/collections/'
    | '/_authenticated/tenants/$tenantSlug/media/'
    | '/_authenticated/tenants/$tenantSlug/plugins/'
    | '/_authenticated/tenants/$tenantSlug/publishing/'
    | '/_authenticated/tenants/$tenantSlug/settings/'
    | '/_authenticated/tenants/$tenantSlug/sync/'
    | '/_authenticated/tenants/$tenantSlug/users/'
    | '/_authenticated/tenants/$tenantSlug/webhooks/'
    | '/_authenticated/tenants/$tenantSlug/collections/$collectionId/'
    | '/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/create'
    | '/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/'
    | '/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/$entryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/sync/': {
      id: '/_authenticated/sync/'
      path: '/sync'
      fullPath: '/sync/'
      preLoaderRoute: typeof AuthenticatedSyncIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants/$tenantSlug': {
      id: '/_authenticated/tenants/$tenantSlug'
      path: '/tenants/$tenantSlug'
      fullPath: '/tenants/$tenantSlug'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhooks/': {
      id: '/_authenticated/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof AuthenticatedWebhooksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhooks/$webhookId': {
      id: '/_authenticated/webhooks/$webhookId'
      path: '/webhooks/$webhookId'
      fullPath: '/webhooks/$webhookId'
      preLoaderRoute: typeof AuthenticatedWebhooksWebhookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhooks/new': {
      id: '/_authenticated/webhooks/new'
      path: '/webhooks/new'
      fullPath: '/webhooks/new'
      preLoaderRoute: typeof AuthenticatedWebhooksNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tenants/': {
      id: '/_authenticated/admin/tenants/'
      path: '/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AuthenticatedAdminTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tenants/$tenantSlug': {
      id: '/_authenticated/admin/tenants/$tenantSlug'
      path: '/tenants/$tenantSlug'
      fullPath: '/admin/tenants/$tenantSlug'
      preLoaderRoute: typeof AuthenticatedAdminTenantsTenantSlugRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tenants/new': {
      id: '/_authenticated/admin/tenants/new'
      path: '/tenants/new'
      fullPath: '/admin/tenants/new'
      preLoaderRoute: typeof AuthenticatedAdminTenantsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/tenants/$tenantSlug/$': {
      id: '/_authenticated/tenants/$tenantSlug/$'
      path: '/$'
      fullPath: '/tenants/$tenantSlug/$'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugSplatRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/settings': {
      id: '/_authenticated/tenants/$tenantSlug/settings'
      path: '/settings'
      fullPath: '/tenants/$tenantSlug/settings'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/ai/import-review': {
      id: '/_authenticated/tenants/$tenantSlug/ai/import-review'
      path: '/ai/import-review'
      fullPath: '/tenants/$tenantSlug/ai/import-review'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugAiImportReviewRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/collections/': {
      id: '/_authenticated/tenants/$tenantSlug/collections/'
      path: '/collections'
      fullPath: '/tenants/$tenantSlug/collections/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/collections/create': {
      id: '/_authenticated/tenants/$tenantSlug/collections/create'
      path: '/collections/create'
      fullPath: '/tenants/$tenantSlug/collections/create'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugCollectionsCreateRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/collections/create-singleton': {
      id: '/_authenticated/tenants/$tenantSlug/collections/create-singleton'
      path: '/collections/create-singleton'
      fullPath: '/tenants/$tenantSlug/collections/create-singleton'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugCollectionsCreateSingletonRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/media/': {
      id: '/_authenticated/tenants/$tenantSlug/media/'
      path: '/media'
      fullPath: '/tenants/$tenantSlug/media/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugMediaIndexRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/plugins/': {
      id: '/_authenticated/tenants/$tenantSlug/plugins/'
      path: '/plugins'
      fullPath: '/tenants/$tenantSlug/plugins/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugPluginsIndexRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/publishing/': {
      id: '/_authenticated/tenants/$tenantSlug/publishing/'
      path: '/publishing'
      fullPath: '/tenants/$tenantSlug/publishing/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugPublishingIndexRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/settings/': {
      id: '/_authenticated/tenants/$tenantSlug/settings/'
      path: '/'
      fullPath: '/tenants/$tenantSlug/settings/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugSettingsRouteRoute
    }
    '/_authenticated/tenants/$tenantSlug/settings/account': {
      id: '/_authenticated/tenants/$tenantSlug/settings/account'
      path: '/account'
      fullPath: '/tenants/$tenantSlug/settings/account'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugSettingsRouteRoute
    }
    '/_authenticated/tenants/$tenantSlug/settings/appearance': {
      id: '/_authenticated/tenants/$tenantSlug/settings/appearance'
      path: '/appearance'
      fullPath: '/tenants/$tenantSlug/settings/appearance'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugSettingsRouteRoute
    }
    '/_authenticated/tenants/$tenantSlug/settings/display': {
      id: '/_authenticated/tenants/$tenantSlug/settings/display'
      path: '/display'
      fullPath: '/tenants/$tenantSlug/settings/display'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugSettingsRouteRoute
    }
    '/_authenticated/tenants/$tenantSlug/settings/notifications': {
      id: '/_authenticated/tenants/$tenantSlug/settings/notifications'
      path: '/notifications'
      fullPath: '/tenants/$tenantSlug/settings/notifications'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugSettingsRouteRoute
    }
    '/_authenticated/tenants/$tenantSlug/sync/': {
      id: '/_authenticated/tenants/$tenantSlug/sync/'
      path: '/sync'
      fullPath: '/tenants/$tenantSlug/sync/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugSyncIndexRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/users/': {
      id: '/_authenticated/tenants/$tenantSlug/users/'
      path: '/users'
      fullPath: '/tenants/$tenantSlug/users/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugUsersIndexRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/webhooks/': {
      id: '/_authenticated/tenants/$tenantSlug/webhooks/'
      path: '/webhooks'
      fullPath: '/tenants/$tenantSlug/webhooks/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugWebhooksIndexRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/webhooks/$webhookId': {
      id: '/_authenticated/tenants/$tenantSlug/webhooks/$webhookId'
      path: '/webhooks/$webhookId'
      fullPath: '/tenants/$tenantSlug/webhooks/$webhookId'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugWebhooksWebhookIdRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/webhooks/new': {
      id: '/_authenticated/tenants/$tenantSlug/webhooks/new'
      path: '/webhooks/new'
      fullPath: '/tenants/$tenantSlug/webhooks/new'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugWebhooksNewRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/collections/$collectionId/': {
      id: '/_authenticated/tenants/$tenantSlug/collections/$collectionId/'
      path: '/collections/$collectionId'
      fullPath: '/tenants/$tenantSlug/collections/$collectionId/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdIndexRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/': {
      id: '/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/'
      path: '/collections/$collectionId/entries'
      fullPath: '/tenants/$tenantSlug/collections/$collectionId/entries/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesIndexRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/create': {
      id: '/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/create'
      path: '/collections/$collectionId/entries/create'
      fullPath: '/tenants/$tenantSlug/collections/$collectionId/entries/create'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesCreateRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
    '/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/$entryId/': {
      id: '/_authenticated/tenants/$tenantSlug/collections/$collectionId/entries/$entryId/'
      path: '/collections/$collectionId/entries/$entryId'
      fullPath: '/tenants/$tenantSlug/collections/$collectionId/entries/$entryId/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesEntryIdIndexRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantSlugRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminTenantsTenantSlugRoute: typeof AuthenticatedAdminTenantsTenantSlugRoute
  AuthenticatedAdminTenantsNewRoute: typeof AuthenticatedAdminTenantsNewRoute
  AuthenticatedAdminTenantsIndexRoute: typeof AuthenticatedAdminTenantsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminTenantsTenantSlugRoute:
      AuthenticatedAdminTenantsTenantSlugRoute,
    AuthenticatedAdminTenantsNewRoute: AuthenticatedAdminTenantsNewRoute,
    AuthenticatedAdminTenantsIndexRoute: AuthenticatedAdminTenantsIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedTenantsTenantSlugSettingsRouteRouteChildren {
  AuthenticatedTenantsTenantSlugSettingsAccountRoute: typeof AuthenticatedTenantsTenantSlugSettingsAccountRoute
  AuthenticatedTenantsTenantSlugSettingsAppearanceRoute: typeof AuthenticatedTenantsTenantSlugSettingsAppearanceRoute
  AuthenticatedTenantsTenantSlugSettingsDisplayRoute: typeof AuthenticatedTenantsTenantSlugSettingsDisplayRoute
  AuthenticatedTenantsTenantSlugSettingsNotificationsRoute: typeof AuthenticatedTenantsTenantSlugSettingsNotificationsRoute
  AuthenticatedTenantsTenantSlugSettingsIndexRoute: typeof AuthenticatedTenantsTenantSlugSettingsIndexRoute
}

const AuthenticatedTenantsTenantSlugSettingsRouteRouteChildren: AuthenticatedTenantsTenantSlugSettingsRouteRouteChildren =
  {
    AuthenticatedTenantsTenantSlugSettingsAccountRoute:
      AuthenticatedTenantsTenantSlugSettingsAccountRoute,
    AuthenticatedTenantsTenantSlugSettingsAppearanceRoute:
      AuthenticatedTenantsTenantSlugSettingsAppearanceRoute,
    AuthenticatedTenantsTenantSlugSettingsDisplayRoute:
      AuthenticatedTenantsTenantSlugSettingsDisplayRoute,
    AuthenticatedTenantsTenantSlugSettingsNotificationsRoute:
      AuthenticatedTenantsTenantSlugSettingsNotificationsRoute,
    AuthenticatedTenantsTenantSlugSettingsIndexRoute:
      AuthenticatedTenantsTenantSlugSettingsIndexRoute,
  }

const AuthenticatedTenantsTenantSlugSettingsRouteRouteWithChildren =
  AuthenticatedTenantsTenantSlugSettingsRouteRoute._addFileChildren(
    AuthenticatedTenantsTenantSlugSettingsRouteRouteChildren,
  )

interface AuthenticatedTenantsTenantSlugRouteChildren {
  AuthenticatedTenantsTenantSlugSettingsRouteRoute: typeof AuthenticatedTenantsTenantSlugSettingsRouteRouteWithChildren
  AuthenticatedTenantsTenantSlugSplatRoute: typeof AuthenticatedTenantsTenantSlugSplatRoute
  AuthenticatedTenantsTenantSlugAiImportReviewRoute: typeof AuthenticatedTenantsTenantSlugAiImportReviewRoute
  AuthenticatedTenantsTenantSlugCollectionsCreateRoute: typeof AuthenticatedTenantsTenantSlugCollectionsCreateRoute
  AuthenticatedTenantsTenantSlugCollectionsCreateSingletonRoute: typeof AuthenticatedTenantsTenantSlugCollectionsCreateSingletonRoute
  AuthenticatedTenantsTenantSlugWebhooksWebhookIdRoute: typeof AuthenticatedTenantsTenantSlugWebhooksWebhookIdRoute
  AuthenticatedTenantsTenantSlugWebhooksNewRoute: typeof AuthenticatedTenantsTenantSlugWebhooksNewRoute
  AuthenticatedTenantsTenantSlugCollectionsIndexRoute: typeof AuthenticatedTenantsTenantSlugCollectionsIndexRoute
  AuthenticatedTenantsTenantSlugMediaIndexRoute: typeof AuthenticatedTenantsTenantSlugMediaIndexRoute
  AuthenticatedTenantsTenantSlugPluginsIndexRoute: typeof AuthenticatedTenantsTenantSlugPluginsIndexRoute
  AuthenticatedTenantsTenantSlugPublishingIndexRoute: typeof AuthenticatedTenantsTenantSlugPublishingIndexRoute
  AuthenticatedTenantsTenantSlugSyncIndexRoute: typeof AuthenticatedTenantsTenantSlugSyncIndexRoute
  AuthenticatedTenantsTenantSlugUsersIndexRoute: typeof AuthenticatedTenantsTenantSlugUsersIndexRoute
  AuthenticatedTenantsTenantSlugWebhooksIndexRoute: typeof AuthenticatedTenantsTenantSlugWebhooksIndexRoute
  AuthenticatedTenantsTenantSlugCollectionsCollectionIdIndexRoute: typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdIndexRoute
  AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesCreateRoute: typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesCreateRoute
  AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesIndexRoute: typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesIndexRoute
  AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesEntryIdIndexRoute: typeof AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesEntryIdIndexRoute
}

const AuthenticatedTenantsTenantSlugRouteChildren: AuthenticatedTenantsTenantSlugRouteChildren =
  {
    AuthenticatedTenantsTenantSlugSettingsRouteRoute:
      AuthenticatedTenantsTenantSlugSettingsRouteRouteWithChildren,
    AuthenticatedTenantsTenantSlugSplatRoute:
      AuthenticatedTenantsTenantSlugSplatRoute,
    AuthenticatedTenantsTenantSlugAiImportReviewRoute:
      AuthenticatedTenantsTenantSlugAiImportReviewRoute,
    AuthenticatedTenantsTenantSlugCollectionsCreateRoute:
      AuthenticatedTenantsTenantSlugCollectionsCreateRoute,
    AuthenticatedTenantsTenantSlugCollectionsCreateSingletonRoute:
      AuthenticatedTenantsTenantSlugCollectionsCreateSingletonRoute,
    AuthenticatedTenantsTenantSlugWebhooksWebhookIdRoute:
      AuthenticatedTenantsTenantSlugWebhooksWebhookIdRoute,
    AuthenticatedTenantsTenantSlugWebhooksNewRoute:
      AuthenticatedTenantsTenantSlugWebhooksNewRoute,
    AuthenticatedTenantsTenantSlugCollectionsIndexRoute:
      AuthenticatedTenantsTenantSlugCollectionsIndexRoute,
    AuthenticatedTenantsTenantSlugMediaIndexRoute:
      AuthenticatedTenantsTenantSlugMediaIndexRoute,
    AuthenticatedTenantsTenantSlugPluginsIndexRoute:
      AuthenticatedTenantsTenantSlugPluginsIndexRoute,
    AuthenticatedTenantsTenantSlugPublishingIndexRoute:
      AuthenticatedTenantsTenantSlugPublishingIndexRoute,
    AuthenticatedTenantsTenantSlugSyncIndexRoute:
      AuthenticatedTenantsTenantSlugSyncIndexRoute,
    AuthenticatedTenantsTenantSlugUsersIndexRoute:
      AuthenticatedTenantsTenantSlugUsersIndexRoute,
    AuthenticatedTenantsTenantSlugWebhooksIndexRoute:
      AuthenticatedTenantsTenantSlugWebhooksIndexRoute,
    AuthenticatedTenantsTenantSlugCollectionsCollectionIdIndexRoute:
      AuthenticatedTenantsTenantSlugCollectionsCollectionIdIndexRoute,
    AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesCreateRoute:
      AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesCreateRoute,
    AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesIndexRoute:
      AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesIndexRoute,
    AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesEntryIdIndexRoute:
      AuthenticatedTenantsTenantSlugCollectionsCollectionIdEntriesEntryIdIndexRoute,
  }

const AuthenticatedTenantsTenantSlugRouteWithChildren =
  AuthenticatedTenantsTenantSlugRoute._addFileChildren(
    AuthenticatedTenantsTenantSlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedTenantsTenantSlugRoute: typeof AuthenticatedTenantsTenantSlugRouteWithChildren
  AuthenticatedWebhooksWebhookIdRoute: typeof AuthenticatedWebhooksWebhookIdRoute
  AuthenticatedWebhooksNewRoute: typeof AuthenticatedWebhooksNewRoute
  AuthenticatedSyncIndexRoute: typeof AuthenticatedSyncIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWebhooksIndexRoute: typeof AuthenticatedWebhooksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedTenantsTenantSlugRoute:
    AuthenticatedTenantsTenantSlugRouteWithChildren,
  AuthenticatedWebhooksWebhookIdRoute: AuthenticatedWebhooksWebhookIdRoute,
  AuthenticatedWebhooksNewRoute: AuthenticatedWebhooksNewRoute,
  AuthenticatedSyncIndexRoute: AuthenticatedSyncIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWebhooksIndexRoute: AuthenticatedWebhooksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
