import type { CommandContext } from '@/commands/engine'
import { executeCommand } from '@/commands/engine'
import { collectionsRepository } from '@/collections/collections.repository'
import { entriesRepository } from '@/entries/entries.repository'
import {
  createPreviewReceipt,
  markPreviewReceiptConsumed,
  verifyPreviewReceipt,
} from '@/ai/preview-receipt.service'
import { ragService } from '@/ai/rag.service'
import type { CommandEnvelope, CommandResult, CommandType } from '@edgecms/schemas/commands'

export interface McpJsonRpcRequest {
  jsonrpc: '2.0'
  id?: string | number | null
  method: string
  params?: Record<string, unknown>
}

export interface McpJsonRpcResponse {
  jsonrpc: '2.0'
  id: string | number | null
  result?: unknown
  error?: {
    code: number
    message: string
    data?: unknown
  }
}

export interface McpToolDefinition {
  name: string
  description: string
  inputSchema: {
    type: 'object'
    properties: Record<string, unknown>
    required?: string[]
  }
}

export const MCP_TOOLS: McpToolDefinition[] = [
  {
    name: 'edgecms_list_collections',
    description: 'List all content collections in the current tenant scope (safe metadata without secrets).',
    inputSchema: {
      type: 'object',
      properties: {
        tenantId: { type: 'string', description: 'Optional tenant ID override' },
      },
    },
  },
  {
    name: 'edgecms_get_schema',
    description: 'Get schema definition, field types, and validation rules for a specific collection.',
    inputSchema: {
      type: 'object',
      required: ['collectionSlug'],
      properties: {
        collectionSlug: { type: 'string', description: 'The unique slug of the collection' },
        tenantId: { type: 'string', description: 'Optional tenant ID override' },
      },
    },
  },
  {
    name: 'edgecms_list_entries',
    description: 'List or query entries from a collection with pagination.',
    inputSchema: {
      type: 'object',
      required: ['collectionSlug'],
      properties: {
        collectionSlug: { type: 'string', description: 'The collection slug' },
        page: { type: 'number', description: 'Page number (default 1)' },
        perPage: { type: 'number', description: 'Items per page (default 20, max 100)' },
        status: { type: 'string', enum: ['draft', 'published', 'scheduled', 'archived'] },
        tenantId: { type: 'string', description: 'Optional tenant ID override' },
      },
    },
  },
  {
    name: 'edgecms_get_entry',
    description: 'Get full content data for an entry by entry ID.',
    inputSchema: {
      type: 'object',
      required: ['entryId'],
      properties: {
        entryId: { type: 'string', description: 'The ID of the entry' },
        tenantId: { type: 'string', description: 'Optional tenant ID override' },
      },
    },
  },
  {
    name: 'edgecms_preview_command',
    description:
      'Dry-run preview an entry or relation mutation through the EdgeCMS Command Engine. Generates an immutable SHA-256 preview receipt required for execution.',
    inputSchema: {
      type: 'object',
      required: ['type', 'payload'],
      properties: {
        type: {
          type: 'string',
          enum: [
            'createEntry',
            'updateEntry',
            'deleteEntry',
            'bulkUpdate',
            'updateSingleton',
            'linkRelation',
            'unlinkRelation',
            'publishNow',
            'unpublishNow',
            'schedulePublish',
            'scheduleUnpublish',
            'cancelSchedule',
          ],
          description: 'Command type to preview',
        },
        payload: {
          type: 'object',
          description: 'Payload specific to the command type',
        },
        optimisticVersion: {
          type: 'number',
          description: 'Expected version number of the target entry for optimistic locking',
        },
      },
    },
  },
  {
    name: 'edgecms_execute_command',
    description:
      'Execute a previously previewed command. Requires the immutable SHA-256 preview receipt generated by edgecms_preview_command.',
    inputSchema: {
      type: 'object',
      required: ['previewReceipt'],
      properties: {
        previewReceipt: {
          type: 'string',
          description: 'The immutable preview receipt ID returned from edgecms_preview_command',
        },
        command: {
          type: 'object',
          description: 'Optional command verification envelope matching the preview receipt',
        },
      },
    },
  },
  {
    name: 'edgecms_search_rag',
    description:
      'Search content semantically using Vectorize RAG across published entries. Supports natural language queries.',
    inputSchema: {
      type: 'object',
      required: ['query'],
      properties: {
        query: { type: 'string', description: 'The natural language search query' },
        collectionSlug: { type: 'string', description: 'Optional collection slug filter' },
        limit: { type: 'number', description: 'Maximum number of results to return (default 5, max 20)' },
        tenantId: { type: 'string', description: 'Optional tenant ID override' },
      },
    },
  },
]

export async function handleMcpToolCall(
  ctx: CommandContext,
  name: string,
  args: Record<string, unknown> = {}
): Promise<{ content: Array<{ type: 'text'; text: string }>; isError?: boolean }> {
  try {
    switch (name) {
      case 'edgecms_list_collections': {
        const tenantId = (args.tenantId as string | undefined) ?? ctx.tenantScope
        const collections = await collectionsRepository.findAll(ctx.db, tenantId)
        const sanitized = collections.map((col) => ({
          id: col.id,
          name: col.name,
          slug: col.slug,
          singleton: col.singleton,
          defaultLocale: col.defaultLocale,
          supportedLocales: col.supportedLocales,
          fieldCount: col.fields.length,
          fieldsSummary: col.fields.map((f) => ({ name: f.name, type: f.type, required: f.required })),
        }))
        return {
          content: [{ type: 'text', text: JSON.stringify(sanitized, null, 2) }],
        }
      }

      case 'edgecms_get_schema': {
        const collectionSlug = args.collectionSlug as string
        const tenantId = (args.tenantId as string | undefined) ?? ctx.tenantScope
        const collection = await collectionsRepository.findBySlug(ctx.db, collectionSlug, tenantId)
        if (!collection) {
          return {
            content: [{ type: 'text', text: `Collection '${collectionSlug}' not found` }],
            isError: true,
          }
        }
        return {
          content: [{ type: 'text', text: JSON.stringify(collection, null, 2) }],
        }
      }

      case 'edgecms_list_entries': {
        const collectionSlug = args.collectionSlug as string
        const tenantId = (args.tenantId as string | undefined) ?? ctx.tenantScope
        const collection = await collectionsRepository.findBySlug(ctx.db, collectionSlug, tenantId)
        if (!collection) {
          return {
            content: [{ type: 'text', text: `Collection '${collectionSlug}' not found` }],
            isError: true,
          }
        }
        const page = Math.max(1, Number(args.page) || 1)
        const perPage = Math.min(100, Math.max(1, Number(args.perPage) || 20))
        const status = args.status as string | undefined

        const entriesResult = await entriesRepository.findAll(ctx.db, {
          collectionId: collection.id,
          tenantId,
          page,
          perPage,
          status,
        })
        return {
          content: [{ type: 'text', text: JSON.stringify(entriesResult, null, 2) }],
        }
      }

      case 'edgecms_get_entry': {
        const entryId = args.entryId as string
        const tenantId = (args.tenantId as string | undefined) ?? ctx.tenantScope
        const entry = await entriesRepository.findById(ctx.db, entryId, tenantId)
        if (!entry) {
          return {
            content: [{ type: 'text', text: `Entry '${entryId}' not found` }],
            isError: true,
          }
        }
        return {
          content: [{ type: 'text', text: JSON.stringify(entry, null, 2) }],
        }
      }

      case 'edgecms_preview_command': {
        const type = args.type as CommandType
        const payload = (args.payload as Record<string, unknown>) || {}
        const optimisticVersion = args.optimisticVersion as number | undefined

        const envelope: CommandEnvelope = {
          type,
          payload,
          optimisticVersion,
          actor: {
            userId: ctx.actor.userId,
            source: 'ai',
          },
          dryRun: true,
          timestamp: new Date().toISOString(),
        }

        // Execute dry-run preview through the Command Engine
        const result = await executeCommand(ctx, envelope)

        // Generate an immutable preview receipt
        const receipt = await createPreviewReceipt({
          commands: [envelope],
          userId: ctx.actor.userId,
          tenantId: ctx.tenantScope,
          kv: ctx.kv,
        })

        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify(
                {
                  status: 'dry_run',
                  commandType: type,
                  diff: result.diff,
                  previewReceipt: receipt.receiptId,
                  sha256Hash: receipt.hash,
                  expiresAt: receipt.expiresAt,
                  message:
                    'Dry-run preview completed successfully. To execute these mutations, call edgecms_execute_command with this previewReceipt.',
                },
                null,
                2
              ),
            },
          ],
        }
      }

      case 'edgecms_execute_command': {
        const previewReceiptId = args.previewReceipt as string
        if (!previewReceiptId) {
          return {
            content: [{ type: 'text', text: 'Error: previewReceipt is required to execute a command' }],
            isError: true,
          }
        }

        // Verify the immutable preview receipt
        const verification = await verifyPreviewReceipt({
          receiptId: previewReceiptId,
          userId: ctx.actor.userId,
          tenantId: ctx.tenantScope,
          kv: ctx.kv,
          commandsToVerify: args.command ? [args.command as CommandEnvelope] : undefined,
        })

        if (!verification.valid || !verification.receipt) {
          return {
            content: [
              {
                type: 'text',
                text: `Preview receipt verification failed: ${verification.message ?? verification.error}`,
              },
            ],
            isError: true,
          }
        }

        if (!verification.receipt.commands || verification.receipt.commands.length === 0) {
          return {
            content: [{ type: 'text', text: 'Preview receipt contains no staged commands' }],
            isError: true,
          }
        }

        const results: CommandResult[] = []
        if (verification.receipt.commands.length === 1) {
          const stagedCommand = verification.receipt.commands[0]!
          const executionEnvelope: CommandEnvelope = {
            ...stagedCommand,
            dryRun: false,
            previewReceipt: previewReceiptId,
            timestamp: new Date().toISOString(),
          }

          const result = await executeCommand(ctx, executionEnvelope)
          results.push(result)

          if (result.status === 'failed') {
            return {
              content: [
                {
                  type: 'text',
                  text: JSON.stringify(
                    {
                      status: 'failed',
                      error: result.error,
                      commandId: result.commandId,
                      results,
                    },
                    null,
                    2
                  ),
                },
              ],
              isError: true,
            }
          }
        } else {
          // Multi-command receipts are executed as a single transaction envelope
          const txEnvelope: CommandEnvelope = {
            type: 'transaction',
            payload: {
              commands: verification.receipt.commands.map((cmd) => ({
                ...cmd,
                dryRun: false,
                previewReceipt: undefined,
              })),
            },
            dryRun: false,
            previewReceipt: previewReceiptId,
            actor: {
              userId: ctx.actor.userId,
              source: 'ai',
            },
            timestamp: new Date().toISOString(),
          }

          const txResult = await executeCommand(ctx, txEnvelope)
          if (txResult.status === 'failed') {
            return {
              content: [
                {
                  type: 'text',
                  text: JSON.stringify(
                    {
                      status: 'failed',
                      error: txResult.error,
                      commandId: txResult.commandId,
                      results: [txResult],
                    },
                    null,
                    2
                  ),
                },
              ],
              isError: true,
            }
          }
          const subResults = (txResult.data?.subResults as CommandResult[] | undefined) ?? [txResult]
          results.push(...subResults)
        }

        await markPreviewReceiptConsumed(previewReceiptId, ctx.kv, ctx.tenantScope)

        const finalData =
          results.length === 1
            ? {
                status: 'success',
                commandId: results[0]?.commandId,
                type: results[0]?.type,
                data: results[0]?.data,
                executedAt: results[0]?.executedAt,
              }
            : {
                status: 'success',
                results,
              }

        return {
          content: [
            {
              type: 'text',
              text: JSON.stringify(finalData, null, 2),
            },
          ],
        }
      }

      case 'edgecms_search_rag': {
        const query = args.query as string
        if (!query || typeof query !== 'string') {
          return {
            content: [{ type: 'text', text: 'Error: query is required for edgecms_search_rag' }],
            isError: true,
          }
        }
        const tenantId = (args.tenantId as string | undefined) ?? ctx.tenantScope
        const collectionSlug = args.collectionSlug as string | undefined
        const limit = Math.min(20, Math.max(1, Number(args.limit) || 5))

        const results = await ragService.searchRag({
          db: ctx.db,
          env: ctx.env,
          query,
          tenantId,
          collectionSlug,
          limit,
        })

        return {
          content: [{ type: 'text', text: JSON.stringify(results, null, 2) }],
        }
      }

      default:
        return {
          content: [{ type: 'text', text: `Unknown MCP tool: ${name}` }],
          isError: true,
        }
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    return {
      content: [{ type: 'text', text: `Tool execution failed: ${message}` }],
      isError: true,
    }
  }
}

/**
 * Handles incoming JSON-RPC 2.0 requests according to Model Context Protocol specification.
 */
export async function processMcpMessage(
  ctx: CommandContext,
  request: McpJsonRpcRequest
): Promise<McpJsonRpcResponse> {
  const { id = null, method, params = {} } = request

  switch (method) {
    case 'initialize': {
      return {
        jsonrpc: '2.0',
        id,
        result: {
          protocolVersion: '2024-11-05',
          capabilities: {
            tools: {},
          },
          serverInfo: {
            name: 'edgecms-mcp-server',
            version: '1.0.0',
          },
        },
      }
    }

    case 'tools/list': {
      return {
        jsonrpc: '2.0',
        id,
        result: {
          tools: MCP_TOOLS,
        },
      }
    }

    case 'tools/call': {
      const toolName = params.name as string
      const toolArgs = (params.arguments as Record<string, unknown>) || {}
      if (!toolName) {
        return {
          jsonrpc: '2.0',
          id,
          error: {
            code: -32602,
            message: 'Missing "name" parameter in tools/call',
          },
        }
      }

      const toolResult = await handleMcpToolCall(ctx, toolName, toolArgs)
      return {
        jsonrpc: '2.0',
        id,
        result: toolResult,
      }
    }

    case 'ping': {
      return {
        jsonrpc: '2.0',
        id,
        result: {},
      }
    }

    default: {
      return {
        jsonrpc: '2.0',
        id,
        error: {
          code: -32601,
          message: `Method not found: ${method}`,
        },
      }
    }
  }
}
